<BUZZ
   A AN THE IS ARE AM BE PM AND OF THEN ALL BOTH EVERYTHING BUT
   EXCEPT \. \, \" \? \! HERE SOME MISS MR DR
   MONEY SO PLEASE>

; "For now, don't recognize buzzwords that previously would just have
   generated a smart response from the parser (i.e., they weren't gonna
   be ignored anyway)"

;<BUZZ
   CAREFULLY CLOSELY SLOWLY CAUTIOUSLY WARILY GENTLY
   QUICKLY RAPIDLY BRIEFLY SUDDENLY SWIFTLY CARELESSLY HASTILY
   HURRIEDLY RECKLESSLY QUIETLY PRIVATELY SILENTLY>

<BUZZ
	AM ;ANY ;COULD ;DID ;DO ;HAS ;HAVE ;HE\'S ;HOW ;HOW\'S
	IS ;IT\'S ;I\'LL ;I\'M ;I\'VE LET\'S ;SHALL ;SHE\'S ;SHOULD
	;THAT\'S ;THEY\'RE WAS ;WERE ;WE\'RE
	;WHEN ;WHEN\'S ;WHICH ;WHY
	;WILL ;WON\'T ;WOULD ;YOU\'RE>

;<BUZZ
	ZERO ONE TWO THREE FOUR FIVE SIX SEVEN EIGHT NINE TEN
	ELEVEN TWELVE THIRTEEN FOURTEEN FIFTEEN SIXTEEN SEVENTEEN EIGHTEEN
	NINETEEN TWENTY THIRTY FORTY FIFTY SIXTY SEVENTY EIGHTY NINETY 
	HUNDRED THOUSAND MILLION BILLION>

;<BUZZ
	FUCK FUCKED CURSE GODDAMNED CUSS DAMN ASSHOLE ASS ;CUNT 
	SHIT SHITHEAD PISS BASTARD FUCKING DAMNED PEE ;COCKSUCKER BITCH>

;<BUZZ
	ZORK XYZZY GRUE GRUES PLUGH YOHO OZMOO GNUSTO WISHBRINGER FROTZ
	MAGICK QUENDOR FROBOZZ>

<BUZZ
	AGAIN G OOPS O>

<SYNONYM NORTH	N>
<SYNONYM SOUTH	S>
<SYNONYM EAST	E>
<SYNONYM WEST	W>
<SYNONYM DOWN	D>
<SYNONYM UP	U>
<SYNONYM NE	NORTHEAST>
<SYNONYM NW	NORTHWEST>
<SYNONYM SE	SOUTHEAST>
<SYNONYM SW	SOUTHWEST>
<PREP-SYNONYM TO TOWARD TOWARDS>
<PREP-SYNONYM WITH USING>
<PREP-SYNONYM THROUGH THRU>
<PREP-SYNONYM ON ONTO ABOARD UPON>
<PREP-SYNONYM IN INSIDE INTO BETWEEN WITHIN>
<PREP-SYNONYM OUT OUTSIDE>
<PREP-SYNONYM UNDER BELOW BENEATH UNDERNEATH>
<PREP-SYNONYM AROUND ALONG>
<PREP-SYNONYM OVER ACROSS>
<PREP-SYNONYM BEHIND BEYOND>
<PREP-SYNONYM AGAINST NEAR>
<PREP-SYNONYM UNTIL TIL TILL>

<SYNTAX $REFRESH = V-REFRESH>
<SYNTAX $VERIFY = V-VERIFY>
<SYNTAX $VERIFY OBJECT = V-VERIFY>
<VERB-SYNONYM $VERIFY $VER>
<SYNTAX ADJUST OBJECT (HELD CARRIED) = V-ADJUST>

<SYNTAX AIM AT OBJECT WITH OBJECT = V-POINT-AT-SWP>
<SYNTAX AIM OBJECT AT OBJECT = V-POINT-AT>
<SYNTAX AIM OBJECT TO OBJECT = V-POINT-AT>

<SYNTAX ANSWER OBJECT (FIND FL-PERSON) = V-REPLY>

<SYNTAX APPROACH OBJECT = V-WALK-TO>

<SYNTAX ARAGON		= V-ARAGON>

<SYNTAX ARREST OBJECT (ON-GROUND IN-ROOM) = V-ARREST>
;<VERB-SYNONYM ARREST DETAIN>

<SYNTAX ASCEND OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>

<SYNTAX ASK ABOUT OBJECT = V-ASK-ABOUT-1>
<SYNTAX ASK FOR OBJECT = V-ASK-FOR-1>
<SYNTAX ASK OBJECT (FIND FL-PERSON) = V-QUESTION>
<SYNTAX ASK OBJECT (ON-GROUND IN-ROOM) ABOUT OBJECT = V-ASK-ABOUT>
<SYNTAX ASK OBJECT (ON-GROUND IN-ROOM) FOR OBJECT = V-ASK-FOR>
<VERB-SYNONYM ASK QUERY INTERROGATE ;QUIZ QUESTION>

<SYNTAX ATTACK OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-KILL>
<VERB-SYNONYM ATTACK ;ASSAULT FIGHT HURT ;INJURE>

<SYNTAX BACK = V-WALK-AROUND>
<SYNTAX BACK AWAY OBJECT (FIND FL-LOCATION) = V-ESCAPE>

<SYNTAX BLOW OBJECT = V-BLOW-INTO>
<SYNTAX BLOW IN OBJECT = V-BLOW-INTO>
<SYNTAX BLOW ON OBJECT = V-BLOW-INTO>
<SYNTAX BLOW THROUGH OBJECT = V-BLOW-INTO>
<SYNTAX BLOW UP OBJECT = V-DETONATE>
<SYNTAX BLOW OUT OBJECT = V-LAMP-OFF>

<SYNTAX BOARD OBJECT (ON-GROUND IN-ROOM) = V-ENTER>
<VERB-SYNONYM BOARD MOUNT>

<SYNTAX BOLEYN		= V-BOLEYN>
;<SYNTAX BOUNCE AROUND OBJECT (FIND FL-LOCATION) (HELD CARRIED HAVE) = V-BOUNCE>
;<VERB-SYNONYM BOUNCE DRIBBLE>
;<SYNTAX BOUNCE OBJECT (FIND FL-LOCATION) (HELD CARRIED HAVE) = V-BOUNCE>

<SYNTAX BOW TO OBJECT (FIND FL-PERSON) = V-BOW>
<SYNTAX BOW BEFORE OBJECT (FIND FL-PERSON) = V-BOW>
<VERB-SYNONYM BOW KNEEL ;GROVEL GENUFLECT>

<SYNTAX BREAK OBJECT (ON-GROUND IN-ROOM HELD CARRIED) WITH OBJECT (FIND FL-BYHAND) (HAVE HELD CARRIED) = V-MUNG>
<SYNTAX BREAK OBJECT (ON-GROUND IN-ROOM) OFF OBJECT (ON-GROUND IN-ROOM) = V-MUNG>
<SYNTAX BREAK DOWN OBJECT (ON-GROUND IN-ROOM HELD CARRIED) WITH OBJECT (HAVE HELD CARRIED) = V-MUNG>
<SYNTAX BREAK IN OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HAVE HELD CARRIED) = V-MUNG>
<SYNTAX BREAK THROUGH OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HAVE HELD CARRIED) = V-MUNG>
<VERB-SYNONYM BREAK DESTROY DAMAGE SMASH ;DEMOLISH WRECK ;CRACK TRASH ERASE>

<SYNTAX BREATHE OBJECT (FIND FL-LOCATION) = V-INHALE>
<SYNTAX BREATHE IN OBJECT (FIND FL-LOCATION) = V-INHALE>
<SYNTAX BREATHE OUT OBJECT (FIND FL-LOCATION) = V-EXHALE>

<SYNTAX BRIEF = V-DESC-LEVEL>

<SYNTAX BRING OBJECT TO OBJECT (ON-GROUND IN-ROOM) = V-GET-FOR>
<SYNTAX BRING OBJECT FOR OBJECT (ON-GROUND IN-ROOM) = V-GET-FOR>
<SYNTAX BRING OBJECT (ON-GROUND IN-ROOM) OBJECT = V-GET-FOR-SWP>

<SYNTAX BURN OBJECT (HAVE TAKE HELD) = V-BURN>
<SYNTAX BURN OBJECT (HAVE TAKE HELD) WITH OBJECT (HELD CARRIED) = V-BURN-WITH>
<SYNTAX BURN DOWN OBJECT (HAVE TAKE HELD) WITH OBJECT (HELD CARRIED) = V-BURN-WITH>
<SYNTAX BURN UP OBJECT (HAVE TAKE HELD) WITH OBJECT (HELD CARRIED) = V-BURN-WITH>
<VERB-SYNONYM BURN KINDLE ;COMBUST ;SCORCH IGNITE ;CHAR ;INCINERAT ;CREMATE>

<SYNTAX BUY OBJECT = V-BUY>
<SYNTAX BUY OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-BUY>
<SYNTAX BUY OBJECT FROM OBJECT = V-BUY-FROM>

<SYNTAX BYE OBJECT (FIND FL-LOCATION) = V-GOODBYE>
<VERB-SYNONYM BYE GOODBYE FAREWELL>

<VERB-SYNONYM CALL HAIL>
<SYNTAX CALL OBJECT (FIND FL-LOCATION) = V-CALL PRE-CALL>
<SYNTAX CALL OBJECT WITH OBJECT = V-CALL PRE-CALL>

<SYNTAX CAST OFF OBJECT (FIND FL-LOCATION) = V-CAST-OFF>

<SYNTAX CLEAN OBJECT = V-CLEAN>
<SYNTAX CLEAN OFF OBJECT = V-CLEAN>
<SYNTAX CLEAN OBJECT (HELD CARRIED HAVE) ON OBJECT = V-CLEAN-OFF>
<SYNTAX CLEAN OBJECT (HELD CARRIED HAVE) OFF OBJECT = V-CLEAN-OFF>
<SYNTAX CLEAN OFF OBJECT (HELD CARRIED HAVE) ON OBJECT = V-CLEAN-OFF>
<SYNTAX CLEAN OBJECT (HELD CARRIED HAVE) OVER OBJECT = V-CLEAN-OFF>
<SYNTAX CLEAN OFF OBJECT (HELD CARRIED HAVE) OVER OBJECT = V-CLEAN-OFF>
<VERB-SYNONYM CLEAN SWEEP WIPE SMEAR BRUSH POLISH>

<SYNTAX CLEVES	= V-CLEVES>

<SYNTAX CLIMB OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX CLIMB ON OBJECT (ON-GROUND IN-ROOM) = V-CLIMB-ON>
<SYNTAX CLIMB UP OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX CLIMB DOWN OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-DOWN>
<SYNTAX CLIMB OVER OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-OVER>
<SYNTAX CLIMB UNDER OBJECT (ON-GROUND IN-ROOM) = V-THROUGH>
<SYNTAX CLIMB IN OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-ENTER>
<SYNTAX CLIMB THROUGH OBJECT (ON-GROUND IN-ROOM) = V-THROUGH>
<SYNTAX CLIMB OUT OBJECT (FIND FL-LOCATION) = V-EXIT>

<SYNTAX CLOSE OBJECT (FIND FL-OPENABLE) (HELD CARRIED ON-GROUND IN-ROOM) = V-CLOSE>
<SYNTAX CLOSE OFF OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LAMP-OFF>
<VERB-SYNONYM CLOSE SLAM>

<SYNTAX CONCEAL OBJECT (HELD CARRIED HAVE) IN OBJECT (ON-GROUND IN-ROOM) = V-PUT PRE-PUT>
<SYNTAX CONCEAL OBJECT (HELD CARRIED HAVE) BEHIND OBJECT (ON-GROUND IN-ROOM) = V-PUT-BEHIND>
<SYNTAX CONCEAL OBJECT (HELD CARRIED HAVE) UNDER OBJECT (ON-GROUND IN-ROOM) = V-PUT-UNDER>

;<VERB-SYNONYM CONNECT ATTACH>
;<SYNTAX CONNECT OBJECT TO OBJECT (ON-GROUND IN-ROOM) = V-PLUG>

<SYNTAX COUNT OBJECT = V-COUNT>
<VERB-SYNONYM COUNT TALLY ;TABULATE>

<VERB-SYNONYM COVER BLOCK SHIELD>
<SYNTAX COVER OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-COVER>
<SYNTAX COVER UP OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-COVER>
<SYNTAX COVER OVER OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-COVER>

;<SYNTAX CROSS OBJECT = V-CROSS>
;<SYNTAX CROSS OVER OBJECT = V-CROSS>
;<VERB-SYNONYM CROSS TRAVERSE>

<VERB-SYNONYM CUT CHOP SLASH ;SLICE ;GASH ;LACERATE> 
<SYNTAX CUT OBJECT WITH OBJECT (FIND FL-KNIFE) (CARRIED HELD HAVE TAKE) = V-CUT>
<SYNTAX CUT UP OBJECT WITH OBJECT (FIND FL-KNIFE) (CARRIED HELD HAVE TAKE) = V-CUT>
<SYNTAX CUT THROUGH OBJECT WITH OBJECT (FIND FL-KNIFE) (HELD CARRIED HAVE TAKE) = V-CUT>
<SYNTAX CUT DOWN OBJECT WITH OBJECT (FIND FL-KNIFE) (CARRIED HELD HAVE TAKE) = V-CUT> 
<SYNTAX CUT OFF OBJECT WITH OBJECT (FIND FL-KNIFE) (CARRIED HELD HAVE TAKE) = V-CUT> 

<SYNTAX DESCEND OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-DOWN>

<VERB-SYNONYM DETONATE EXPLODE>
<SYNTAX DETONATE OBJECT = V-DETONATE>

<SYNTAX DIAGNOSE OBJECT (ON-GROUND IN-ROOM HELD CARRIED) WITH OBJECT (FIND FL-BYHAND) = V-DIAGNOSE>

;<VERB-SYNONYM DIG EXCAVATE>
;<SYNTAX DIG IN OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-DIG>
;<SYNTAX DIG AT OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-DIG>
;<SYNTAX DIG UP OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-DIG>
;<SYNTAX DIG WITH OBJECT (HELD CARRIED HAVE) IN OBJECT (ON-GROUND IN-ROOM) = V-DIG-SWP>
;<SYNTAX DIG THROUGH OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-DIG>
;<SYNTAX DIG OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-DIG>

<SYNTAX DISEMBARK OBJECT (FIND FL-LOCATION) = V-EXIT>
<SYNTAX DISEMBARK FROM OBJECT = V-EXIT>
<SYNTAX DISEMBARK OUT OBJECT = V-EXIT>

<SYNTAX DIVE OBJECT (FIND FL-LOCATION) = V-DIVE>
<SYNTAX DIVE DOWN OBJECT (FIND FL-LOCATION) = V-DIVE>
<SYNTAX DIVE IN OBJECT (FIND FL-LOCATION) = V-DIVE>
<SYNTAX DIVE UNDER OBJECT (FIND FL-LOCATION) = V-DIVE>
<SYNTAX DIVE OVER OBJECT = V-LEAP>

<SYNTAX DRESS OBJECT (FIND FL-LOCATION) = V-DRESS>

<VERB-SYNONYM DRINK SIP GUZZLE IMBIBE QUAFF SWILL>
<SYNTAX DRINK OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-DRINK>
<SYNTAX DRINK FROM OBJECT (HELD CARRIED) = V-DRINK-FROM>

<SYNTAX DRIVE OBJECT (FIND FL-LOCATION) = V-DRIVE>
<SYNTAX DRIVE TO OBJECT (FIND FL-LOCATION) = V-DRIVE>

<VERB-SYNONYM DROP DUMP>
<SYNTAX DROP OBJECT (HELD MANY) = V-DROP PRE-DROP>
<SYNTAX DROP OBJECT (HELD MANY HAVE) DOWN OBJECT = V-PUT PRE-PUT>
<SYNTAX DROP OBJECT (HELD MANY) IN OBJECT = V-PUT PRE-PUT>
<SYNTAX DROP OBJECT (HELD MANY HAVE) ON OBJECT = V-PUT-ON PRE-PUT-ON>

;<SYNTAX DUCK = V-DUCK>
;<SYNTAX DUCK UNDER OBJECT = V-STAND-UNDER>

<SYNTAX EAT OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-EAT>
<VERB-SYNONYM EAT SWALLOW BITE>

<SYNTAX EMBARK OBJECT (FIND FL-LOCATION) = V-ENTER>
<SYNTAX EMBARK ON OBJECT = V-ENTER>

<VERB-SYNONYM EMPTY CLEAR>
<SYNTAX EMPTY OBJECT (HELD CARRIED HAVE) = V-EMPTY>
<SYNTAX EMPTY OUT OBJECT (HELD CARRIED HAVE) = V-EMPTY>
<SYNTAX EMPTY OFF OBJECT (HELD CARRIED HAVE) = V-EMPTY>
<SYNTAX EMPTY OBJECT FROM OBJECT = V-TAKE PRE-TAKE>
<SYNTAX EMPTY OUT OBJECT FROM OBJECT = V-TAKE PRE-TAKE>
<SYNTAX EMPTY OBJECT OUT OBJECT = V-TAKE PRE-TAKE>
<SYNTAX EMPTY OBJECT (HELD CARRIED HAVE) IN OBJECT = V-EMPTY-INTO>
<SYNTAX EMPTY OBJECT (HELD CARRIED HAVE) ON OBJECT = V-EMPTY-INTO>
<SYNTAX EMPTY OUT OBJECT (HELD CARRIED HAVE) IN OBJECT = V-EMPTY-INTO>
<SYNTAX EMPTY OUT OBJECT (HELD CARRIED HAVE) ON OBJECT = V-EMPTY-INTO>

<SYNTAX ENTER OBJECT (FIND FL-LOCATION) = V-ENTER>

<SYNTAX ESCAPE OBJECT (FIND FL-LOCATION) = V-ESCAPE>
<SYNTAX ESCAPE FROM OBJECT (ON-GROUND IN-ROOM) = V-ESCAPE>
<SYNTAX ESCAPE AWAY OBJECT (FIND FL-LOCATION) = V-ESCAPE>
<VERB-SYNONYM ESCAPE FLEE>

<SYNTAX EXAMINE OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-EXAMINE PRE-EXAMINE>
<SYNTAX EXAMINE IN OBJECT (HELD CARRIED IN-ROOM ON-GROUND) = V-LOOK-INSIDE>
<SYNTAX EXAMINE ON OBJECT (HELD CARRIED IN-ROOM ON-GROUND) = V-EXAMINE PRE-EXAMINE>
<SYNTAX EXAMINE FOR OBJECT = V-FIND>
<SYNTAX EXAMINE OBJECT (HELD CARRIED ON-GROUND IN-ROOM) THROUGH OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LOOK-THRU>
<SYNTAX EXAMINE OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LOOK-THRU>
<VERB-SYNONYM EXAMINE X INSPECT DESCRIBE CHECK STUDY SURVEY SEE TRACE>

<SYNTAX EXHALE OBJECT (FIND FL-LOCATION) = V-EXHALE>

<VERB-SYNONYM EXIT DEPART SCRAM WITHDRAW>
<SYNTAX EXIT OBJECT (FIND FL-LOCATION) = V-EXIT>

<VERB-SYNONYM EXTINGUISH DOUSE QUENCH SNUFF>
<SYNTAX EXTINGUISH OBJECT (FIND FL-LAMP) = V-LAMP-OFF>

<SYNTAX FEED OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-FOOD) (HELD CARRIED HAVE) = V-FEED-SWP>
<SYNTAX FEED OBJECT (HELD CARRIED HAVE) TO OBJECT (FIND FL-ALIVE) (ON-GROUND IN-ROOM) = V-FEED PRE-FEED>
<SYNTAX FEED OBJECT (ON-GROUND IN-ROOM) OBJECT (FIND FL-FOOD) (HELD CARRIED HAVE) = V-FEED-SWP>

<SYNTAX FEEL OBJECT = V-TOUCH>
<SYNTAX FEEL IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-REACH-IN>
<SYNTAX FELL OBJECT WITH OBJECT (FIND FL-KNIFE) (CARRIED HELD HAVE TAKE) = V-CUT>

<SYNTAX FILL OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT = V-FILL>
<SYNTAX FILL OBJECT (HELD CARRIED ON-GROUND IN-ROOM) AT OBJECT = V-FILL>
<SYNTAX FIND OBJECT = V-FIND>
<VERB-SYNONYM FIND SEEK DISCOVER>

<SYNTAX FIX OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-REPAIR>
<SYNTAX FIX UP OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-REPAIR>

;<SYNTAX FLASH OBJECT (HELD CARRIED HAVE) AT OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
;<SYNTAX FLASH OBJECT (HELD CARRIED HAVE) IN OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
;<SYNTAX FLASH OBJECT (HELD CARRIED HAVE) ON OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
;<SYNTAX FLASH OBJECT (HELD CARRIED HAVE) OVER OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>

;<SYNTAX FLATTEN OBJECT (HELD CARRIED HAVE) = V-FOLD>
;<SYNTAX FLATTEN OUT OBJECT (HELD CARRIED HAVE) = V-FOLD>

<SYNTAX FLIP OBJECT = V-FLIP>

<SYNTAX FLY = V-FLY>
<SYNTAX FLY OBJECT = V-FLY>
<SYNTAX FLY ON OBJECT = V-FLY>
<SYNTAX FLY WITH OBJECT = V-FLY>
<SYNTAX FLY OVER OBJECT = V-FLY>

<SYNTAX FOCUS OBJECT (HELD CARRIED) = V-ADJUST>
<SYNTAX FOCUS ON OBJECT = V-FOCUS-ON>
<SYNTAX FOCUS OBJECT ON OBJECT = V-FOCUS-ON>
<SYNTAX FOCUS OBJECT AT OBJECT = V-FOCUS-ON>

<SYNTAX FOLD OBJECT (HELD CARRIED HAVE) = V-FOLD>
<SYNTAX FOLD UP OBJECT (HELD CARRIED HAVE) = V-FOLD>
<SYNTAX FOLD OBJECT (HELD CARRIED HAVE) AROUND OBJECT (ON-GROUND IN-ROOM) = V-WRAP-AROUND>
<SYNTAX FOLD OBJECT IN OBJECT = V-WRAP-AROUND-SWP>
<SYNTAX FOLD UP OBJECT (ON-GROUND IN-ROOM) IN OBJECT (HELD CARRIED HAVE) = V-WRAP-AROUND-SWP>
<SYNTAX FOLD OUT OBJECT (HELD CARRIED HAVE) = V-UNFOLD>
<VERB-SYNONYM FOLD WRAP>

<SYNTAX FOLLOW OBJECT = V-FOLLOW>
<VERB-SYNONYM FOLLOW PURSUE CHASE>
<SYNTAX FOO OBJECT (FIND FL-LOCATION) = V-FOO>

<SYNTAX GET OBJECT (FIND FL-TAKEABLE) (ON-GROUND IN-ROOM CARRIED MANY) = V-TAKE PRE-TAKE>
<SYNTAX GET IN OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-ENTER>
<SYNTAX GET OUT OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-EXIT>
<SYNTAX GET ON OBJECT (ON-GROUND IN-ROOM) = V-CLIMB-ON>
<SYNTAX GET UP OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-RAISE>
<SYNTAX GET DOWN OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-LOWER>
<SYNTAX GET UNDER OBJECT (ON-GROUND IN-ROOM) = V-STAND-UNDER>
<SYNTAX GET OBJECT (IN-ROOM CARRIED MANY) OUT OBJECT = V-TAKE PRE-TAKE>
<SYNTAX GET OBJECT (IN-ROOM CARRIED MANY) OFF OBJECT = V-TAKE PRE-TAKE>
<SYNTAX GET OBJECT (IN-ROOM CARRIED MANY) FROM OBJECT = V-TAKE PRE-TAKE>
<SYNTAX GET OBJECT (IN-ROOM CARRIED MANY) IN OBJECT = V-TAKE PRE-TAKE>
<SYNTAX GET OBJECT (IN-ROOM CARRIED MANY) ON OBJECT = V-TAKE PRE-TAKE>
<SYNTAX GET OBJECT (IN-ROOM CARRIED MANY) WITH OBJECT (HELD CARRIED HAVE) = V-TAKE-WITH>
<SYNTAX GET OFF OBJECT = V-TAKE-OFF>
<SYNTAX GET AWAY OBJECT (FIND FL-LOCATION) = V-ESCAPE>
<SYNTAX GET OBJECT (ON-GROUND IN-ROOM) OBJECT = V-GET-FOR-SWP>
<SYNTAX GET OBJECT FOR OBJECT (ON-GROUND IN-ROOM) = V-GET-FOR>
<SYNTAX GET OBJECT TO OBJECT (ON-GROUND IN-ROOM) = V-GET-FOR>

<SYNTAX GIN = V-GIN>

<SYNTAX GO = V-WALK-AROUND>
<SYNTAX GO OBJECT = V-WALK>
<SYNTAX GO IN OBJECT (FIND FL-LOCATION) = V-ENTER>
<SYNTAX GO OUT OBJECT (FIND FL-LOCATION) = V-EXIT>
<SYNTAX GO ON OBJECT = V-STAND-ON>
<SYNTAX GO OVER OBJECT = V-CROSS>
<SYNTAX GO THROUGH OBJECT = V-THROUGH>
<SYNTAX GO AROUND OBJECT (FIND FL-LOCATION) = V-WALK-AROUND>
<SYNTAX GO BEHIND OBJECT = V-WALK-AROUND>
<SYNTAX GO UNDER OBJECT = V-THROUGH>
<SYNTAX GO UP OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX GO DOWN OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-DOWN>
<SYNTAX GO TO OBJECT = V-WALK-TO>
<SYNTAX GO AWAY OBJECT (FIND FL-LOCATION) = V-ESCAPE>
<SYNTAX GO FROM OBJECT = V-ESCAPE>

<SYNTAX GUESS OBJECT (FIND FL-LOCATION) = V-GUESS>

<VERB-SYNONYM HAGGLE BARGAIN NEGOTIATE DICKER DEAL>
<SYNTAX HAGGLE WITH OBJECT (ON-GROUND IN-ROOM) (FIND FL-PERSON) = V-HAGGLE>

<VERB-SYNONYM HAND GIVE ;DONATE DELIVER OFFER LOAN LEND ;BESTOW> 
<SYNTAX HAND OBJECT (HELD CARRIED HAVE TAKE MANY) TO OBJECT (FIND FL-PERSON) (IN-ROOM ON-GROUND) = V-GIVE PRE-GIVE>
<SYNTAX HAND OBJECT (ON-GROUND IN-ROOM) OBJECT (HELD CARRIED HAVE TAKE MANY) = V-GIVE-SWP>

<SYNTAX HAUL OBJECT = V-HAUL>
<SYNTAX HAUL IN OBJECT = V-HAUL>
<SYNTAX HAUL UP OBJECT = V-HAUL>

<SYNTAX HEAR OBJECT = V-LISTEN PRE-LISTEN>

<SYNTAX HEAT OBJECT (HAVE TAKE HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-HEAT>
<SYNTAX HEAT OBJECT (HAVE TAKE HELD CARRIED ON-GROUND IN-ROOM) OVER OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-HEAT>
<VERB-SYNONYM HEAT WARM>

;<SYNTAX HEEL OBJECT (FIND FL-LOCATION) = V-HEEL>

<VERB-SYNONYM HELLO HI GREETINGS GREET SALUTE>
<SYNTAX HELLO OBJECT (FIND FL-LOCATION) = V-HELLO>

<SYNTAX HELP = V-HINT>
<VERB-SYNONYM HELP HINT HINTS CLUE CLUES INVISICLUES>
<SYNTAX HELP OBJECT = V-RESCUE>
<SYNTAX HELP OFF OBJECT (FIND FL-LOCATION) = V-HINTS-NO>

<SYNTAX HIDE OBJECT (FIND FL-LOCATION) = V-HIDE>
<SYNTAX HIDE BEHIND OBJECT = V-HIDE>
<SYNTAX HIDE OBJECT (HELD CARRIED HAVE) BEHIND OBJECT (ON-GROUND IN-ROOM) = V-PUT-BEHIND>
<SYNTAX HIDE OBJECT (HELD CARRIED HAVE) UNDER OBJECT (ON-GROUND IN-ROOM) = V-PUT-UNDER>
<SYNTAX HIDE IN OBJECT = V-ENTER>
<SYNTAX HIDE UNDER OBJECT = V-STAND-UNDER>

<SYNTAX HIT OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-HIT>
<SYNTAX HIT AT OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-HIT>
<VERB-SYNONYM HIT SLAP WHACK SWAT>

<SYNTAX HOLD OBJECT (FIND FL-TAKEABLE) (ON-GROUND IN-ROOM MANY) = V-TAKE PRE-TAKE>
<SYNTAX HOLD ON OBJECT (FIND FL-TAKEABLE) (ON-GROUND IN-ROOM) = V-TAKE PRE-TAKE>
<SYNTAX HOLD UP OBJECT (FIND FL-LOCATION) (HELD CARRIED HAVE) = V-RAISE>
<SYNTAX HOLD OBJECT (HELD CARRIED HAVE) IN OBJECT = V-PUT PRE-PUT>
<SYNTAX HOLD OBJECT (HELD CARRIED HAVE) ON OBJECT = V-TOUCH-TO>
<SYNTAX HOLD OBJECT (HELD CARRIED HAVE) OVER OBJECT = V-HOLD-OVER>
<SYNTAX HOLD OBJECT (HELD CARRIED HAVE) AGAINST OBJECT = V-TOUCH-TO>
<SYNTAX HOLD OBJECT (HELD CARRIED HAVE) TO OBJECT = V-TOUCH-TO>
<SYNTAX HOLD OBJECT (HELD CARRIED HAVE) UP OBJECT = V-TOUCH-TO>
<SYNTAX HOLD DOWN OBJECT (ON-GROUND IN-ROOM HELD CARRIED) = V-LOWER>
<SYNTAX HOLD APART OBJECT (ON-GROUND IN-ROOM) = V-OPEN>

<SYNTAX HOWARD		= V-HOWARD>

<SYNTAX HUSH = V-HUSH>
<VERB-SYNONYM HUSH SHUSH SHH SHHH SHHHH SSHH SSHHH QUIET>

<SYNTAX ILLUMINATE OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-LIGHTED) (HELD CARRIED HAVE) = V-SHINE-AT-SWP>

;<SYNTAX INFLATE OBJECT = V-BLOW-INTO>

<VERB-SYNONYM INHALE HYPERVENT>
<SYNTAX INHALE OBJECT (FIND FL-LOCATION) = V-INHALE>

<SYNTAX INVENTORY = V-INVENTORY>
<VERB-SYNONYM INVENTORY I>

;<SYNTAX JOSTLE OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-SHAKE>
;<VERB-SYNONYM JOSTLE RATTLE>

<SYNTAX JUMP OBJECT (FIND FL-LOCATION) = V-LEAP>
<SYNTAX JUMP UP OBJECT (FIND FL-LOCATION) = V-CLIMB-UP>
<SYNTAX JUMP DOWN OBJECT (FIND FL-LOCATION) = V-CLIMB-DOWN>
<SYNTAX JUMP ON OBJECT = V-STAND-ON>
<SYNTAX JUMP OVER OBJECT = V-CLIMB-OVER>
<SYNTAX JUMP IN OBJECT (FIND FL-LOCATION) = V-LEAP>
<SYNTAX JUMP TO OBJECT = V-ENTER>
<SYNTAX JUMP THROUGH OBJECT = V-ENTER>
<SYNTAX JUMP OUT OBJECT (FIND FL-LOCATION) = V-EXIT>
<SYNTAX JUMP FROM OBJECT = V-CLIMB-DOWN>
<SYNTAX JUMP OFF OBJECT (FIND FL-LOCATION) = V-CLIMB-DOWN>
<VERB-SYNONYM JUMP LEAP BOUND HURDLE VAULT>

<SYNTAX KICK OBJECT = V-KICK>
<SYNTAX KICK AROUND OBJECT = V-KICK>
<SYNTAX KICK IN OBJECT = V-MUNG>
<SYNTAX KICK DOWN OBJECT = V-KICK>

<VERB-SYNONYM KILL MURDER ;SLAY STAB PUNCH WOUND ;DISPATCH> 
<SYNTAX KILL OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-KILL>

<SYNTAX KISS OBJECT (FIND FL-PERSON) (ON-GROUND IN-ROOM) = V-KISS>
<VERB-SYNONYM KISS SMOOCH>

<SYNTAX KNOCK AT OBJECT = V-KNOCK>
<SYNTAX KNOCK ON OBJECT = V-KNOCK>
<SYNTAX KNOCK DOWN OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-HIT>
<SYNTAX KNOCK OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-HIT>
<SYNTAX KNOCK OUT OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-HIT>
<VERB-SYNONYM KNOCK RAP POUND TAP>

<SYNTAX LAND OBJECT (FIND FL-LOCATION) = V-LAND>

<SYNTAX LAUNCH OBJECT (FIND FL-LOCATION) = V-LAUNCH>

<SYNTAX LEAN ON OBJECT = V-PUSH>

<SYNTAX LEAVE OBJECT (FIND FL-LOCATION) = V-EXIT>
<SYNTAX LEAVE OBJECT (HELD CARRIED MANY) IN OBJECT (ON-GROUND IN-ROOM CARRIED) = V-PUT PRE-PUT>
<SYNTAX LEAVE OBJECT (HELD CARRIED MANY) ON OBJECT (ON-GROUND IN-ROOM CARRIED) = V-PUT-ON PRE-PUT-ON>

<SYNTAX LET GO OBJECT = V-RELEASE>
<SYNTAX LET OBJECT (HELD CARRIED HAVE) GO OBJECT (FIND FL-BYHAND) = V-RELEASE>

<SYNTAX LIE DOWN OBJECT (FIND FL-LOCATION) = V-LIE-DOWN>
<SYNTAX LIE ON OBJECT = V-LIE-DOWN>
<SYNTAX LIE IN OBJECT = V-LIE-DOWN>
;<VERB-SYNONYM LIE RECLINE REPOSE>

<SYNTAX LIGHT OBJECT (ON-GROUND IN-ROOM) = V-LIGHT>
<SYNTAX LIGHT OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-LIGHT-WITH PRE-LIGHT-WITH>
<SYNTAX LIGHT OBJECT (ON-GROUND IN-ROOM) FROM OBJECT (HELD CARRIED HAVE) = V-LIGHT-WITH PRE-LIGHT-WITH>
<SYNTAX LIGHT UP OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-LIGHT-WITH PRE-LIGHT-WITH>
<SYNTAX LIGHT UP OBJECT (ON-GROUND IN-ROOM) FROM OBJECT (HELD CARRIED HAVE) = V-LIGHT-WITH PRE-LIGHT-WITH>

<SYNTAX LISTEN OBJECT (FIND FL-LOCATION) = V-LISTEN PRE-LISTEN>
<SYNTAX LISTEN TO OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LISTEN PRE-LISTEN>
<SYNTAX LISTEN IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LISTEN PRE-LISTEN>
<SYNTAX LISTEN FOR OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LISTEN PRE-LISTEN>
<SYNTAX LISTEN TO OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT = V-LISTEN PRE-LISTEN>
<SYNTAX LISTEN TO OBJECT (HELD CARRIED ON-GROUND IN-ROOM) THROUGH OBJECT = V-LISTEN PRE-LISTEN>

<SYNTAX LOCK OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) = V-LOCK>

;<SYNTAX LOO = V-LOO>

<SYNTAX LOOK = V-LOOK>
<SYNTAX LOOK AT OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-EXAMINE PRE-EXAMINE>
<SYNTAX LOOK AROUND OBJECT (FIND FL-LOCATION) = V-LOOK>
<SYNTAX LOOK DOWN OBJECT (FIND FL-LOCATION) = V-LOOK-DOWN>
<SYNTAX LOOK OVER OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-EXAMINE PRE-EXAMINE>
<SYNTAX LOOK UP OBJECT (FIND FL-LOCATION) = V-LOOK-UP>
<SYNTAX LOOK OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-DUMB-EXAMINE PRE-DUMB-EXAMINE>
<SYNTAX LOOK THROUGH OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LOOK-INSIDE> 
<SYNTAX LOOK THROUGH OBJECT AT OBJECT = V-LOOK-THRU-SWP>
<SYNTAX LOOK UNDER OBJECT = V-LOOK-UNDER>
<SYNTAX LOOK BEHIND OBJECT = V-LOOK-BEHIND>
<SYNTAX LOOK IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LOOK-INSIDE>
<SYNTAX LOOK ON OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LOOK-ON>
<SYNTAX LOOK AT OBJECT (HELD CARRIED ON-GROUND IN-ROOM) THROUGH OBJECT = V-LOOK-THRU>
<SYNTAX LOOK AT OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT = V-LOOK-THRU>
<SYNTAX LOOK IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) THROUGH OBJECT = V-LOOK-THRU>
<SYNTAX LOOK IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT = V-LOOK-THRU>
<SYNTAX LOOK OUT OBJECT (FIND FL-LOCATION) = V-LOOK-OUTSIDE>
<SYNTAX LOOK FOR OBJECT = V-FIND>
<SYNTAX LOOK TO OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-EXAMINE PRE-EXAMINE>
<VERB-SYNONYM LOOK L STARE GAZE PEER PEEK>

<VERB-SYNONYM LOOSEN JIGGLE WIGGLE WOBBLE HOOK>
<SYNTAX LOOSEN OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE TAKE) = V-LOOSEN>

<SYNTAX LOWER OBJECT = V-LOWER>

<SYNTAX MAKE OBJECT = V-MAKE>
<SYNTAX MAKE UP OBJECT = V-MAKE>
<SYNTAX MAKE OBJECT OBJECT = V-MAKE>

<SYNTAX ECHO ;MARX = V-ECHO ;V-MARX>
<VERB-SYNONYM ECHO GROUCHO HARPO CHICO GUMMO ZEPPO PUNT WHISTLE SING HUM MARX>

<SYNTAX MAYBE = V-MAYBE>

<SYNTAX MELT OBJECT (HELD CARRIED HAVE) WITH OBJECT (HELD CARRIED HAVE) (FIND FL-LIGHTED) = V-MELT>

<SYNTAX MOVE OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-MOVE>
<SYNTAX MOVE OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX MOVE OBJECT (ON-GROUND IN-ROOM) OBJECT = V-PUSH-TO>
<SYNTAX MOVE OBJECT (ON-GROUND IN-ROOM) TO OBJECT = V-PUSH-TO>
<VERB-SYNONYM MOVE SHIFT ROLL DISLOCATE>

<SYNTAX NO = V-NO>
;<VERB-SYNONYM NO N>	; "This could never be used anyway"

<SYNTAX NOD AT OBJECT (FIND FL-PERSON) = V-WAVE-AT>
<SYNTAX NOD TO OBJECT (FIND FL-PERSON) = V-WAVE-AT>
<VERB-SYNONYM NOD SMILE LAUGH GRIN SNEER MOTION ;BECKON>

<SYNTAX NOTIFY = V-NOTIFY>

<SYNTAX OPEN OBJECT (FIND FL-OPENABLE) (TAKE HELD CARRIED ON-GROUND IN-ROOM) = V-OPEN>
<SYNTAX OPEN UP OBJECT (FIND FL-OPENABLE) (TAKE HELD CARRIED ON-GROUND IN-ROOM) = V-OPEN>
<SYNTAX OPEN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-OPEN-WITH>
<SYNTAX OPEN UP OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-OPEN-WITH>
;<VERB-SYNONYM OPEN UNSEAL DISASSEMBLE>

<SYNTAX PADDLE OBJECT = V-PADDLE>
<SYNTAX PADDLE WITH OBJECT (HELD CARRIED HAVE) = V-PADDLE-WITH>
<SYNTAX PADDLE OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-PADDLE-WITH>

<SYNTAX PARR		= V-PARR>
<SYNTAX PASSWORD OBJECT = V-PASSWORD>

<SYNTAX PAT OBJECT = V-TOUCH>

<VERB-SYNONYM PAY BRIBE ENTICE ;RENUMERATE>
<SYNTAX PAY OBJECT WITH OBJECT (FIND FL-MONEY) (TAKE HAVE HELD CARRIED) = V-PAY>
<SYNTAX PAY OBJECT (HELD CARRIED HAVE TAKE MANY) TO OBJECT (FIND FL-MONEY) (IN-ROOM ON-GROUND) = V-GIVE PRE-GIVE>
<SYNTAX PAY OBJECT (ON-GROUND IN-ROOM) OBJECT (HELD CARRIED HAVE TAKE MANY) = V-GIVE-SWP>

<SYNTAX PET OBJECT = V-TOUCH>

<SYNTAX PICK OBJECT (FIND FL-TAKEABLE) (ON-GROUND MANY) = V-TAKE PRE-TAKE>
<SYNTAX PICK OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-PICK>
<SYNTAX PICK UP OBJECT (FIND FL-TAKEABLE) (ON-GROUND MANY) = V-TAKE PRE-TAKE>

<VERB-SYNONYM PLAY FIDDLE TOY ;CAVORT>
<SYNTAX PLAY OBJECT (FIND FL-LOCATION) = V-PLAY>
<SYNTAX PLAY WITH OBJECT = V-PLAY>

;<SYNTAX PLUG IN OBJECT = V-PLUG>
;<SYNTAX PLUG OBJECT IN OBJECT (ON-GROUND IN-ROOM) = V-PLUG>

<SYNTAX POCKET OBJECT (HELD CARRIED) = V-POCKET PRE-POCKET>

<SYNTAX POINT OBJECT = V-POINT>
<SYNTAX POINT AT OBJECT = V-POINT>
<SYNTAX POINT AT OBJECT FOR OBJECT (FIND FL-ALIVE) = V-POINT>
<SYNTAX POINT TO OBJECT = V-POINT>
<SYNTAX POINT TO OBJECT FOR OBJECT (FIND FL-ALIVE) = V-POINT>
<SYNTAX POINT OUT OBJECT TO OBJECT (FIND FL-ALIVE) = V-POINT>
<SYNTAX POINT AT OBJECT WITH OBJECT = V-POINT-AT-SWP>
<SYNTAX POINT OBJECT AT OBJECT = V-POINT-AT>
<SYNTAX POINT OBJECT TO OBJECT = V-POINT-AT>

<VERB-SYNONYM POKE JAB BLIND>
<SYNTAX POKE OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-MUNG>

<SYNTAX POUR OBJECT (HELD CARRIED HAVE) = V-POUR>
<SYNTAX POUR OUT OBJECT (HELD CARRIED HAVE) = V-POUR>
<SYNTAX POUR OBJECT (HELD CARRIED HAVE) IN OBJECT = V-EMPTY-INTO>
<SYNTAX POUR OUT OBJECT (HELD CARRIED HAVE) IN OBJECT = V-EMPTY-INTO>
<SYNTAX POUR OBJECT (HELD CARRIED HAVE) ON OBJECT = V-EMPTY-INTO>
<SYNTAX POUR OUT OBJECT (HELD CARRIED HAVE) ON OBJECT = V-EMPTY-INTO>
<SYNTAX POUR OBJECT FROM OBJECT (HELD CARRIED HAVE) = V-POUR-FROM>
<SYNTAX POUR OBJECT OUT OBJECT (HELD CARRIED HAVE) = V-POUR-FROM>
<SYNTAX POUR OUT OBJECT FROM OBJECT (HELD CARRIED HAVE) = V-POUR-FROM>
<VERB-SYNONYM POUR SPILL SPRINKLE>

<SYNTAX PRAY = V-PRAY>

;<SYNTAX PRY OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE TAKE) = V-LOOSEN>
;<SYNTAX PRY OUT OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE TAKE) = V-LOOSEN>
;<SYNTAX PRY UP OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE TAKE) = V-LOOSEN>

<SYNTAX PULL OBJECT (ON-GROUND IN-ROOM) = V-PULL>
<SYNTAX PULL ON OBJECT (ON-GROUND IN-ROOM) = V-PULL>
<SYNTAX PULL ON OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PULL UP OBJECT (ON-GROUND IN-ROOM) = V-RAISE>
<SYNTAX PULL UP OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PULL DOWN OBJECT (ON-GROUND IN-ROOM) = V-LOWER>
<SYNTAX PULL DOWN OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PULL OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PULL OBJECT OUT OBJECT (ON-GROUND IN-ROOM) = V-TAKE PRE-TAKE>
<SYNTAX PULL OBJECT (ON-GROUND IN-ROOM) OBJECT = V-PUSH-TO>
<SYNTAX PULL OBJECT (ON-GROUND IN-ROOM) TO OBJECT = V-PUSH-TO>
<SYNTAX PULL OBJECT (ON-GROUND IN-ROOM) FROM OBJECT (ON-GROUND IN-ROOM) = V-TAKE PRE-TAKE>
<SYNTAX PULL APART OBJECT (ON-GROUND IN-ROOM) = V-OPEN>
<SYNTAX PULL OUT OBJECT = V-UNPLUG>
<VERB-SYNONYM PULL TUG DRAG YANK>

<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) = V-PUSH>
<SYNTAX PUSH ON OBJECT (IN-ROOM ON-GROUND) = V-PUSH>
<SYNTAX PUSH OFF OBJECT (FIND FL-LOCATION) (IN-ROOM ON-GROUND) = V-LAUNCH>
<SYNTAX PUSH UP OBJECT (IN-ROOM ON-GROUND) = V-RAISE>
<SYNTAX PUSH DOWN OBJECT (IN-ROOM ON-GROUND) = V-LOWER>
<SYNTAX PUSH IN OBJECT (IN-ROOM ON-GROUND) = V-PLUG>
<SYNTAX PUSH OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PUSH DOWN OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PUSH ON OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) OBJECT = V-PUSH-TO>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) TO OBJECT = V-PUSH-TO>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) IN OBJECT = V-PUSH-TO>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) ON OBJECT = V-PUSH-TO>
<SYNTAX PUSH OBJECT (IN-ROOM ON-GROUND) OVER OBJECT = V-PUSH-TO>
<SYNTAX PUSH OBJECT (ON-GROUND IN-ROOM) AT OBJECT = V-PUSH-TO>
<SYNTAX PUSH OBJECT (ON-GROUND IN-ROOM) UNDER OBJECT = V-PUT-UNDER>

<SYNTAX PUT OBJECT (HELD CARRIED MANY) IN OBJECT = V-PUT PRE-PUT>
<SYNTAX PUT OBJECT (HELD CARRIED HAVE MANY) DOWN OBJECT = V-PUT PRE-PUT>
<SYNTAX PUT OBJECT (HELD CARRIED HAVE MANY) ON OBJECT = V-PUT-ON PRE-PUT-ON>
<SYNTAX PUT OBJECT (HELD CARRIED HAVE) AGAINST OBJECT = V-TOUCH-TO>
<SYNTAX PUT OBJECT (HELD CARRIED HAVE) THROUGH OBJECT (ON-GROUND IN-ROOM CARRIED) = V-THROW PRE-THROW>
<SYNTAX PUT OBJECT (HELD CARRIED HAVE) OVER OBJECT = V-PUT-ON PRE-PUT-ON>
<SYNTAX PUT DOWN OBJECT (HELD CARRIED HAVE MANY) = V-DROP PRE-DROP>
<SYNTAX PUT OBJECT (HELD HAVE CARRIED MANY) UNDER OBJECT (ON-GROUND IN-ROOM CARRIED) = V-PUT-UNDER> 
<SYNTAX PUT ON OBJECT (ON-GROUND IN-ROOM CARRIED) = V-WEAR>
<SYNTAX PUT OBJECT (HELD CARRIED MANY HAVE) BEHIND OBJECT (ON-GROUND IN-ROOM CARRIED) = V-PUT-BEHIND>
<SYNTAX PUT OUT OBJECT (ON-GROUND IN-ROOM CARRIED HELD) = V-LAMP-OFF>
<VERB-SYNONYM PUSH PRESS SHOVE THRUST NUDGE STICK>
<VERB-SYNONYM PUT STUFF INSERT PLACE LAY ;STASH>

<SYNTAX QUIT = V-QUIT>
<VERB-SYNONYM QUIT Q>

<VERB-SYNONYM RAISE LIFT ELEVATE HOIST>
<SYNTAX RAISE OBJECT = V-RAISE>
<SYNTAX RAISE UP OBJECT = V-RAISE>
<SYNTAX RAISE OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX RAISE UP OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>

;<VERB-SYNONYM RAPE MOLEST DEFILE RAVISH HUMP>
;<SYNTAX RAPE OBJECT (FIND FL-ALIVE) = V-RAPE>

<VERB-SYNONYM REACH GROPE>
<SYNTAX REACH OBJECT WITH OBJECT (FIND FL-TOOL) = V-TOUCH-TO-SWP>
<SYNTAX REACH FOR OBJECT WITH OBJECT (FIND FL-TOOL) = V-TOUCH-TO-SWP>
<SYNTAX REACH OUT OBJECT WITH OBJECT (FIND FL-TOOL) = V-TOUCH-TO-SWP>
<SYNTAX REACH TO OBJECT WITH OBJECT (FIND FL-TOOL) = V-TOUCH-TO-SWP>
<SYNTAX REACH IN OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-REACH-IN>
<SYNTAX REACH THROUGH OBJECT (ON-GROUND IN-ROOM) = V-REACH-IN>

<SYNTAX READ OBJECT (FIND FL-READABLE) (TAKE HELD CARRIED ON-GROUND IN-ROOM) = V-READ>
<SYNTAX READ THROUGH OBJECT (FIND FL-READABLE) (TAKE HELD CARRIED ON-GROUND IN-ROOM) = V-READ>
<SYNTAX READ OBJECT (TAKE HELD CARRIED ON-GROUND IN-ROOM) THROUGH OBJECT = V-LOOK-THRU>
<SYNTAX READ OBJECT (TAKE HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT = V-LOOK-THRU>
<SYNTAX READ OBJECT (TAKE HELD CARRIED ON-GROUND IN-ROOM) TO OBJECT (FIND FL-PERSON) = V-READ-TO>
<SYNTAX READ OBJECT OBJECT (FIND FL-READABLE) (TAKE HELD CARRIED ON-GROUND IN-ROOM) = V-READ-TO-SWP>
<VERB-SYNONYM READ SKIM BROWSE LEAF>

<SYNTAX REFUSE OBJECT = V-REFUSE>

<VERB-SYNONYM RELEASE FREE UNJAM>
<SYNTAX RELEASE OBJECT (ON-GROUND IN-ROOM HELD CARRIED) WITH OBJECT (FIND FL-BYHAND) (HAVE) = V-RELEASE>
<SYNTAX RELEASE OBJECT (ON-GROUND IN-ROOM HELD CARRIED) FROM OBJECT (FIND FL-BYHAND) = V-RELEASE>

<SYNTAX REMOVE OBJECT (FIND FL-WORN) (HELD CARRIED) = V-TAKE-OFF>
<SYNTAX REMOVE OBJECT (ON-GROUND IN-ROOM MANY) FROM OBJECT = V-TAKE PRE-TAKE>
<SYNTAX REMOVE OBJECT (ON-GROUND IN-ROOM MANY) ON OBJECT = V-TAKE PRE-TAKE>
<SYNTAX REMOVE OBJECT (ON-GROUND IN-ROOM MANY) IN OBJECT = V-TAKE PRE-TAKE>
<SYNTAX REMOVE OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-TAKE-WITH> 

<SYNTAX RENT OBJECT = V-FOO>

<SYNTAX REPAIR OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-REPAIR>
<VERB-SYNONYM REPAIR SERVICE>

<SYNTAX REPLACE OBJECT = V-REPLACE>

<VERB-SYNONYM REPLY RESPOND ;RETORT>
<SYNTAX REPLY TO OBJECT (FIND FL-PERSON) = V-REPLY>

<VERB-SYNONYM RESCUE AID PRESERVE ASSIST>
<SYNTAX RESCUE OBJECT (FIND FL-PERSON) = V-RESCUE>

<SYNTAX RESTART	= V-RESTART>
<SYNTAX RESTORE	= V-RESTORE>

<SYNTAX RETRACT OBJECT = V-FOLD>

<SYNTAX RETREAT = V-WALK-AROUND>
<SYNTAX RETREAT FROM OBJECT = V-ESCAPE>
<SYNTAX RETREAT AWAY OBJECT (FIND FL-LOCATION) = V-ESCAPE>

<SYNTAX RIDE OBJECT = V-RIDE>
<SYNTAX RIDE IN OBJECT = V-RIDE>
<SYNTAX RIDE ON OBJECT = V-RIDE>

<SYNTAX RING OBJECT = V-RING>

;<SYNTAX RIP DOWN OBJECT WITH OBJECT (FIND FL-BYHAND) (CARRIED HELD HAVE TAKE) = V-RIP>
;<SYNTAX RIP OBJECT WITH OBJECT (FIND FL-BYHAND) (CARRIED HELD HAVE TAKE) = V-RIP>
<SYNTAX RIP UP OBJECT WITH OBJECT (FIND FL-BYHAND) (CARRIED HELD HAVE TAKE) = V-RIP>
<SYNTAX RIP THROUGH OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE TAKE) = V-RIP> 
<SYNTAX RIP OFF OBJECT (FIND FL-TAKEABLE) = V-TAKE PRE-TAKE>
<VERB-SYNONYM RIP TEAR>

<SYNTAX ROB OBJECT = V-ROB>
<SYNTAX ROB OBJECT FROM OBJECT = V-STEAL>

<SYNTAX ROW OBJECT OBJECT (FIND FL-LOCATION) = V-ROW>

<SYNTAX RUB OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-RUB-WITH>

<SYNTAX SAVE		= V-SAVE>
<SYNTAX SAVE OBJECT = V-RESCUE>

<SYNTAX SAY OBJECT (FIND FL-LOCATION) = V-SAY>
<SYNTAX SAY OBJECT TO OBJECT (ON-GROUND IN-ROOM) = V-SAY>
<SYNTAX SAY TO OBJECT (ON-GROUND IN-ROOM) = V-TELL>
<VERB-SYNONYM SAY TALK SPEAK UTTER PROCLAIM ;MAYBE>



<SYNTAX SCALE UP OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX SCALE OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX SCALE DOWN OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-DOWN>
<SYNTAX SCALE OVER OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-OVER>

<SYNTAX SCORE     = V-SCORE>

;<SYNTAX SCREW DOWN OBJECT (HELD CARRIED HAVE) IN OBJECT (ON-GROUND IN-ROOM) = V-SCREW>
;<SYNTAX SCREW DOWN OBJECT (HELD CARRIED HAVE) ON OBJECT (ON-GROUND IN-ROOM) = V-SCREW>
;<SYNTAX SCREW DOWN OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-SCREW-WITH>
;<SYNTAX SCREW IN OBJECT (HELD CARRIED HAVE) ON OBJECT (ON-GROUND IN-ROOM) = V-SCREW>
;<SYNTAX SCREW IN OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-SCREW-WITH>
;<SYNTAX SCREW OBJECT (HELD CARRIED HAVE) IN OBJECT (ON-GROUND IN-ROOM) = V-SCREW>
;<SYNTAX SCREW OBJECT (HELD CARRIED HAVE) ON OBJECT (ON-GROUND IN-ROOM) = V-SCREW>
;<SYNTAX SCREW OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-SCREW-WITH>
;<VERB-SYNONYM SCREW TIGHTEN>

<SYNTAX SCRIPT		= V-SCRIPT>

<VERB-SYNONYM SEARCH RUMMAGE FRISK RANSACK SIFT>
<SYNTAX SEARCH OBJECT = V-SEARCH>
<SYNTAX SEARCH IN OBJECT = V-SEARCH>
<SYNTAX SEARCH FOR OBJECT = V-FIND>
<SYNTAX SEARCH UNDER OBJECT = V-LOOK-UNDER>
<SYNTAX SEARCH THROUGH OBJECT = V-SEARCH>

<SYNTAX SELL OBJECT (HELD CARRIED HAVE) TO OBJECT (FIND FL-PERSON) (ON-GROUND IN-ROOM) = V-SELL>
<SYNTAX SELL OBJECT (ON-GROUND IN-ROOM) OBJECT (HELD CARRIED HAVE TAKE) = V-SELL-SWP>

<SYNTAX SET OFF OBJECT = V-DETONATE>
<SYNTAX SET OBJECT TO OBJECT = V-TUNE-TO>
<SYNTAX SET OBJECT AT OBJECT = V-TUNE-TO>

<SYNTAX SEYMOUR	= V-SEYMOUR>

<SYNTAX SHAKE OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-SHAKE>
<SYNTAX SHAKE OUT OBJECT (HELD CARRIED HAVE) = V-EMPTY>
<SYNTAX SHAKE OUT OBJECT (HELD CARRIED HAVE) IN OBJECT = V-EMPTY-INTO>
<SYNTAX SHAKE OUT OBJECT FROM OBJECT (HELD CARRIED HAVE) = V-POUR-FROM>

<SYNTAX SHINE OBJECT (HELD CARRIED HAVE) AT OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
<SYNTAX SHINE OBJECT (HELD CARRIED HAVE) IN OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
<SYNTAX SHINE OBJECT (HELD CARRIED HAVE) ON OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
<SYNTAX SHINE OBJECT (HELD CARRIED HAVE) OVER OBJECT (ON-GROUND IN-ROOM) = V-SHINE-AT>
<SYNTAX SHINE ON OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-LIGHTED) (HELD CARRIED HAVE) = V-SHINE-AT-SWP>
<SYNTAX SHINE IN OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-LIGHTED) (HELD CARRIED HAVE) = V-SHINE-AT-SWP>
<SYNTAX SHINE OVER OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-LIGHTED) (HELD CARRIED HAVE) = V-SHINE-AT-SWP>

<VERB-SYNONYM SHOOT FIRE>
<SYNTAX SHOOT OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-SHOOT PRE-SHOOT>
<SYNTAX SHOOT OBJECT (HAVE TAKE HELD CARRIED) AT OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-SHOOT-SWP>
<SYNTAX SHOOT OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT (HAVE TAKE HELD CARRIED) (FIND FL-WEAPON) = V-SHOOT PRE-SHOOT>

<VERB-SYNONYM SHOW DISPLAY>
<SYNTAX SHOW OBJECT (HELD CARRIED ON-GROUND IN-ROOM) TO OBJECT (FIND FL-PERSON) (HELD CARRIED IN-ROOM ON-GROUND) = V-SHOW PRE-SHOW>
<SYNTAX SHOW OBJECT OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-SHOW-SWP>

<SYNTAX SHUT UP OBJECT (FIND FL-LOCATION) = V-HUSH>
<SYNTAX SHUT OBJECT (FIND FL-OPENABLE) (HELD CARRIED ON-GROUND IN-ROOM) = V-CLOSE>
<SYNTAX SHUT OFF OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LAMP-OFF>

<SYNTAX SIT OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-SIT> 
<SYNTAX SIT ON OBJECT (ON-GROUND IN-ROOM) = V-SIT>
<SYNTAX SIT DOWN OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-SIT>
<SYNTAX SIT IN OBJECT (ON-GROUND IN-ROOM) = V-ENTER>
<SYNTAX SIT AT OBJECT = V-SIT>
<VERB-SYNONYM SIT SETTLE SQUAT CROUCH>

<SYNTAX SLEEP = V-LIE-DOWN>
<SYNTAX SLEEP IN OBJECT (IN-ROOM ON-GROUND) = V-LIE-DOWN>
<SYNTAX SLEEP ON OBJECT (IN-ROOM ON-GROUND) = V-LIE-DOWN>
<VERB-SYNONYM SLEEP NAP SNOOZE REST>

<SYNTAX SLIDE OBJECT = V-MOVE>
<SYNTAX SLIDE OBJECT TO OBJECT = V-PUSH-TO>
<SYNTAX SLIDE OBJECT (HELD CARRIED HAVE TAKE) UNDER OBJECT = V-PUT-UNDER>
<SYNTAX SLIDE OBJECT (HELD CARRIED HAVE TAKE) IN OBJECT = V-PUT PRE-PUT>
<SYNTAX SLIDE OBJECT (HELD CARRIED HAVE TAKE) DOWN OBJECT = V-PUT PRE-PUT>
<SYNTAX SLIDE DOWN OBJECT (FIND FL-LOCATION) = V-CLIMB-DOWN>

<SYNTAX SMELL OBJECT (FIND FL-LOCATION) = V-SMELL>
<VERB-SYNONYM SMELL SNIFF WHIFF>

<SYNTAX SMOKE OBJECT (HAVE HELD CARRIED) = V-SMOKE>

<SYNTAX SPIN OBJECT (FIND FL-LOCATION) = V-SPIN>
<SYNTAX SPIN OBJECT TO OBJECT = V-TUNE-TO>
<SYNTAX SPIN OBJECT OBJECT = V-TUNE-TO>
<VERB-SYNONYM SPIN WHIRL>

;<SYNTAX SQUEEZE OBJECT (HELD CARRIED HAVE) ON OBJECT (ON-GROUND IN-ROOM) = V-PUT PRE-PUT>
;<SYNTAX SQUEEZE OBJECT = V-SQUEEZE>
;<VERB-SYNONYM SQUEEZE SQUASH SQUISH CRUSH CRUMPLE>
;<SYNTAX STAMP DOWN OBJECT = V-MUNG>
;<SYNTAX STAMP ON OBJECT = V-MUNG>
;<SYNTAX STAMP OVER OBJECT = V-MUNG>
;<VERB-SYNONYM STAMP TRAMPLE>

<VERB-SYNONYM STAND RISE>
<SYNTAX STAND = V-STAND>
<SYNTAX STAND UP OBJECT (FIND FL-LOCATION) = V-STAND>
<SYNTAX STAND ON OBJECT = V-STAND-ON>
<SYNTAX STAND IN OBJECT = V-STAND-ON>
<SYNTAX STAND UNDER OBJECT = V-STAND-UNDER>

<SYNTAX START OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LAMP-ON>
<SYNTAX START OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT (HELD CARRIED HAVE) = V-LAMP-ON>

<SYNTAX STEAL OBJECT (MANY) = V-STEAL>
<SYNTAX STEAL OBJECT (MANY) FROM OBJECT (FIND FL-PERSON) = V-STEAL>
<SYNTAX STEAL OBJECT (MANY) OUT OBJECT = V-STEAL>
<VERB-SYNONYM STEAL PINCH>

<SYNTAX STOP OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LAMP-OFF>

<SYNTAX STRIKE OBJECT (TAKE HELD CARRIED) WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE)= V-STRIKE>

;<SYNTAX SUCK = V-SUCK>

<SYNTAX SUPER		= V-DESC-LEVEL>
<VERB-SYNONYM SUPER SUPERBRIEF>

<VERB-SYNONYM SWIM BATHE WADE>
<SYNTAX SWIM OBJECT (FIND FL-LOCATION) = V-SWIM>
<SYNTAX SWIM DOWN OBJECT (FIND FL-LOCATION) = V-DIVE>
<SYNTAX SWIM IN OBJECT = V-SWIM>
<SYNTAX SWIM TO OBJECT = V-SWIM>
<SYNTAX SWIM THROUGH OBJECT = V-SWIM>
<SYNTAX SWIM OVER OBJECT = V-SWIM>
<SYNTAX SWIM UNDER OBJECT = V-DIVE>

<SYNTAX SWING OBJECT (HELD CARRIED HAVE) = V-SWING>
<SYNTAX SWING OBJECT (HELD CARRIED HAVE) AT OBJECT (FIND FL-PERSON) (ON-GROUND IN-ROOM) = V-SWING>
<SYNTAX SWING ON OBJECT = V-CLIMB-ON>

<SYNTAX SWORDFISH = V-SWORDFISH>

<VERB-SYNONYM TAKE GRAB KEEP CATCH CARRY SEIZE SNATCH RETRIEVE> 
<SYNTAX TAKE OBJECT (FIND FL-TAKEABLE) (ON-GROUND IN-ROOM CARRIED MANY) = V-TAKE PRE-TAKE>
<SYNTAX TAKE UP OBJECT (FIND FL-LOCATION) = V-RAISE>
<SYNTAX TAKE DOWN OBJECT (FIND FL-LOCATION) = V-LOWER>
<SYNTAX TAKE OBJECT (IN-ROOM CARRIED MANY) TO OBJECT = V-PUSH-TO>
<SYNTAX TAKE OBJECT (IN-ROOM CARRIED MANY) OUT OBJECT = V-TAKE PRE-TAKE>
<SYNTAX TAKE OBJECT (IN-ROOM CARRIED MANY) OFF OBJECT = V-TAKE PRE-TAKE>
<SYNTAX TAKE OBJECT (IN-ROOM CARRIED MANY) FROM OBJECT = V-TAKE PRE-TAKE>
<SYNTAX TAKE OBJECT (IN-ROOM CARRIED MANY) IN OBJECT = V-TAKE PRE-TAKE>
<SYNTAX TAKE OBJECT (IN-ROOM CARRIED MANY) ON OBJECT = V-TAKE PRE-TAKE>
<SYNTAX TAKE OBJECT (IN-ROOM CARRIED MANY) WITH OBJECT (HELD CARRIED HAVE) = V-TAKE-WITH>
<SYNTAX TAKE APART OBJECT (ON-GROUND IN-ROOM) = V-OPEN>
<SYNTAX TAKE OFF OBJECT (FIND FL-WORN) (HELD CARRIED) = V-TAKE-OFF>

<VERB-SYNONYM TASTE LICK>
<SYNTAX TASTE OBJECT = V-TASTE>

<SYNTAX TELL OBJECT (FIND FL-PERSON) (IN-ROOM) = V-TELL>
<SYNTAX TELL OBJECT (IN-ROOM) ABOUT OBJECT = V-TELL-ABOUT>
<SYNTAX TELL ABOUT OBJECT = V-TELL-WHO>

<SYNTAX THANK = V-THANK>
<SYNTAX THANK OBJECT = V-THANK>
<VERB-SYNONYM THANK THANKS>

<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) = V-DROP PRE-DROP>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) AT OBJECT (ON-GROUND IN-ROOM) = V-THROW PRE-THROW>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) TO OBJECT (ON-GROUND IN-ROOM) = V-THROW PRE-THROW>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) OFF OBJECT = V-THROW-OVER PRE-THROW-OVER>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) OVER OBJECT = V-THROW-OVER PRE-THROW-OVER>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) THROUGH OBJECT (ON-GROUND IN-ROOM) = V-PUT PRE-PUT>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) DOWN OBJECT (ON-GROUND IN-ROOM) = V-PUT PRE-PUT>
<SYNTAX THROW OBJECT (HELD MANY CARRIED) IN OBJECT (ON-GROUND IN-ROOM) = V-PUT PRE-PUT>
<SYNTAX THROW OBJECT (HELD MANY CARRIED HAVE) ON OBJECT (ON-GROUND IN-ROOM) = V-PUT PRE-PUT>
<SYNTAX THROW AWAY OBJECT (HELD MANY CARRIED HAVE) = V-DROP PRE-DROP>
<SYNTAX THROW OBJECT (ON-GROUND IN-ROOM) OBJECT (HELD MANY CARRIED HAVE) = V-THROW-SWP>
<VERB-SYNONYM THROW TOSS HURL CHUCK FLING PITCH>

<VERB-SYNONYM TIE FASTEN SECURE>
<SYNTAX TIE OBJECT (ON-GROUND IN-ROOM MANY) = V-TIE>
<SYNTAX TIE OBJECT (ON-GROUND IN-ROOM MANY) TO OBJECT (FIND FL-LOCATION) = V-TIE>
<SYNTAX TIE OBJECT (ON-GROUND IN-ROOM MANY) WITH OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM HELD CARRIED) = V-TIE-UP>
<SYNTAX TIE UP OBJECT (ON-GROUND IN-ROOM MANY) WITH OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM HELD CARRIED) = V-TIE-UP>

<SYNTAX TIP OBJECT = V-TIP>

<VERB-SYNONYM TOUCH DISTURB SCRATCH>
<SYNTAX TOUCH OBJECT = V-TOUCH>
<SYNTAX TOUCH OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-TOUCH-TO-SWP>
<SYNTAX TOUCH OBJECT (HELD CARRIED HAVE) TO OBJECT = V-TOUCH-TO>

<SYNTAX TRANSLATE OBJECT = V-TRANSLATE>

;<VERB-SYNONYM TUNE DIAL>
<SYNTAX ;TUNE DIAL OBJECT TO OBJECT = V-TUNE-TO>

<SYNTAX TURN OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE TAKE) = V-TURN>
<SYNTAX TURN THROUGH OBJECT = V-READ>
<SYNTAX TURN TO OBJECT = V-TURN-TO>
<SYNTAX TURN ON OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LAMP-ON>
<SYNTAX TURN OFF OBJECT (HELD CARRIED ON-GROUND IN-ROOM) = V-LAMP-OFF>
<SYNTAX TURN AROUND OBJECT (FIND FL-LOCATION) = V-SPIN>
<SYNTAX TURN OVER OBJECT = V-FLIP>
<SYNTAX TURN OBJECT TO OBJECT = V-TUNE-TO>
<SYNTAX TURN OBJECT OBJECT = V-TUNE-TO>
<SYNTAX TURN DOWN OBJECT = V-TURN-DOWN>
<SYNTAX TURN UP OBJECT = V-TURN-UP>
<VERB-SYNONYM TURN ROTATE TOGGLE TWIST>

<VERB-SYNONYM UNDRESS DISROBE STRIP>
<SYNTAX UNDRESS OBJECT (FIND FL-LOCATION) = V-UNDRESS>

<SYNTAX UNFOLD OBJECT (HELD CARRIED HAVE) = V-UNFOLD>
<VERB-SYNONYM UNFOLD UNFLATTEN EXTEND>

<SYNTAX UNLOCK OBJECT (ON-GROUND IN-ROOM) WITH OBJECT (FIND FL-BYHAND) = V-UNLOCK>

;<VERB-SYNONYM UNPLUG DISCONNEC DETACH UNATTACH DISENGAGE>
;<SYNTAX UNPLUG OBJECT = V-UNPLUG>
;<SYNTAX UNPLUG OBJECT FROM OBJECT (ON-GROUND IN-ROOM) = V-UNPLUG>

;<SYNTAX UNSCREW OBJECT (ON-GROUND IN-ROOM HELD CARRIED) WITH OBJECT (FIND FL-TOOL) (HELD CARRIED HAVE TAKE) = V-UNSCREW>
<SYNTAX UNSCREW OBJECT (ON-GROUND IN-ROOM HELD CARRIED) FROM OBJECT = V-UNSCREW-FROM>
<SYNTAX UNSCREW OBJECT (ON-GROUND IN-ROOM HELD CARRIED) OUT OBJECT = V-UNSCREW-FROM>

<SYNTAX UNSCRIPT	= V-SCRIPT>

<SYNTAX UNTIE OBJECT = V-UNTIE>
<VERB-SYNONYM UNTIE UNDO UNFASTEN UNHOOK>

<VERB-SYNONYM USE EMPLOY EXPLOIT OPERATE>
<SYNTAX USE OBJECT = V-USE>
<SYNTAX USE OBJECT ON OBJECT = V-USE-ON>

<SYNTAX VERBOSE	= V-DESC-LEVEL>

<SYNTAX VERSION	= V-VERSION>

<VERB-SYNONYM WAIT STAY LOITER Z>
<SYNTAX WAIT OBJECT (FIND FL-LOCATION) = V-WAIT>
<SYNTAX WAIT FOR OBJECT = V-WAIT-FOR>
<SYNTAX WAIT UNTIL OBJECT = V-WAIT-FOR>

<VERB-SYNONYM WAKE AWAKE AWAKEN ROUSE REVIVE>
<SYNTAX WAKE OBJECT (FIND FL-LOCATION) = V-ALARM>
<SYNTAX WAKE UP OBJECT (FIND FL-LOCATION) = V-ALARM>

<SYNTAX WALK = V-WALK-AROUND>
<SYNTAX WALK OBJECT = V-WALK>
<SYNTAX WALK IN OBJECT (FIND FL-LOCATION) = V-ENTER>
<SYNTAX WALK OUT OBJECT (FIND FL-LOCATION) = V-EXIT>
<SYNTAX WALK ON OBJECT = V-STAND-ON>
<SYNTAX WALK OVER OBJECT = V-CROSS>
<SYNTAX WALK THROUGH OBJECT = V-THROUGH>
<SYNTAX WALK AROUND OBJECT (FIND FL-LOCATION) = V-WALK-AROUND>
<SYNTAX WALK BEHIND OBJECT = V-WALK-AROUND>
<SYNTAX WALK UNDER OBJECT = V-THROUGH>
<SYNTAX WALK UP OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-UP>
<SYNTAX WALK DOWN OBJECT (FIND FL-LOCATION) (ON-GROUND IN-ROOM) = V-CLIMB-DOWN>
<SYNTAX WALK TO OBJECT = V-WALK-TO>
<SYNTAX WALK FROM OBJECT = V-ESCAPE>
<SYNTAX WALK AWAY OBJECT (FIND FL-LOCATION) = V-ESCAPE>
<VERB-SYNONYM WALK PROCEED STEP TRUDGE HIKE>

<SYNTAX WATCH OBJECT (FIND FL-LOCATION) (HELD CARRIED ON-GROUND IN-ROOM) = V-WATCH PRE-WATCH>
<SYNTAX WATCH OBJECT (HELD CARRIED ON-GROUND IN-ROOM) THROUGH OBJECT = V-LOOK-THRU>
<SYNTAX WATCH OBJECT (HELD CARRIED ON-GROUND IN-ROOM) WITH OBJECT = V-LOOK-THRU>
<VERB-SYNONYM WATCH OBSERVE>

<SYNTAX WAVE OBJECT = V-SWING>
<SYNTAX WAVE AT OBJECT (FIND FL-PERSON) = V-WAVE-AT>
<SYNTAX WAVE TO OBJECT (FIND FL-PERSON) = V-WAVE-AT> 

<VERB-SYNONYM WEAR DON>
<SYNTAX WEAR OBJECT = V-WEAR>

<VERB-SYNONYM WEDGE FORCE>
<SYNTAX WEDGE OBJECT (HELD CARRIED HAVE) IN OBJECT = V-WEDGE>
<SYNTAX WEDGE OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>
<SYNTAX WEDGE UP OBJECT WITH OBJECT (HELD CARRIED HAVE) = V-LOOSEN>

<SYNTAX WEIGH OBJECT = V-WEIGH>

<SYNTAX WHAT OBJECT = V-WHAT>
<SYNTAX WHAT ABOUT OBJECT = V-WHAT>
<VERB-SYNONYM WHAT WHATS WHAT\'S>

<SYNTAX WHERE OBJECT = V-WHERE>
<VERB-SYNONYM WHERE WHERES WHERE\'S>

<SYNTAX WHO OBJECT = V-WHO>
<VERB-SYNONYM WHO WHOS WHO\'S>

<SYNTAX WIND OBJECT = V-WIND>
<SYNTAX WIND UP OBJECT = V-WIND>
<SYNTAX WIND OBJECT (HELD CARRIED HAVE) AROUND OBJECT (ON-GROUND IN-ROOM) = V-WRAP-AROUND>
<SYNTAX WIND OBJECT (ON-GROUND IN-ROOM) IN OBJECT (HELD CARRIED HAVE) = V-WRAP-AROUND-SWP>
<SYNTAX WIND UP OBJECT (ON-GROUND IN-ROOM) IN OBJECT (HELD CARRIED HAVE) = V-WRAP-AROUND-SWP>

<SYNTAX WORK ON OBJECT WITH OBJECT (FIND FL-BYHAND) (HELD CARRIED HAVE) = V-REPAIR>

<VERB-SYNONYM YELL SCREAM SHOUT HOWL CRY>
<SYNTAX YELL OBJECT (FIND FL-LOCATION) = V-YELL>
<SYNTAX YELL AT OBJECT = V-YELL>
<SYNTAX YELL TO OBJECT = V-YELL>

<SYNTAX YES			= V-YES>
<VERB-SYNONYM YES Y>

